# Background and foreground colors
background = #020101
foreground = #F4F8F5

# Standard colors
palette = 0=#020101
palette = 1=#9f685e
palette = 2=#BEC19F
palette = 3=#9B9B77
palette = 4=#B4BED8
palette = 5=#9A94AB
palette = 6=#A8C4D0
palette = 7=#F4F8F5

# Bright colors
palette = 8=#615959
palette = 9=#c98a7d
palette = 10=#cbd18a
palette = 11=#c0c292
palette = 12=#b8c9ff
palette = 13=#c0b8d6
palette = 14=#98d6f3
palette = 15=#d6f5dc
