$color = rgba(2, 1, 1, 1)
$inner_color = rgba(2, 1, 1, 0.66)
$outer_color = rgba(154, 148, 171, 1)
$font_color = rgba(244, 248, 245, 1)
$placeholder_color = rgba(244, 248, 245, 0.7)
$check_color = rgba(168, 196, 208, 1)
